### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by plegrand1** [step-/gtkmenuplus#5]
Hello,
I'm trying to run gtkmenuplus on a debian +mate installation and I get this error message when launching gtkmenuplus: 
`no such file or directory.`
I suspect that a package is missing to make it work.
Could you please tell me what are the prerequisites (packages) for everything to work properly?
Thanks for your help

**Comment by step-** [comment]
Hi,

gtkmenuplus requires GTK2 or GTK3 libraries. You can check which libraries are missing (look for "not found") by running command `ldd /usr/bin/gtkmenuplus` (or wherever you have installed the gtkmenuplus binary file) in a terminal window.

Did you build gtkmenuplus yourself after downloading the source code?  You must build for GTK3 because recent Debian doesn't install GTK2 by default.

Did you instead download a pre-built tar.gz package from this repo's release page? Be wary that the package is built for GTK2 and it can't work in a recent Debian unless you can also install GTK2.

**Comment by plegrand1** [comment]
I downloaded gtkmenuplus here: https://oldforum.puppylinux.com/viewtopic.php?t=107982

By the way, what does "remove" in the file name mean.
When I run the` ldd gtkmenuplus` command, I get this message:` is not a dynamic executable`
Thanks for your help

**Comment by plegrand1** [comment]
I made some test and it appears that the gtkmenuplus-i686 doesnt works but the gtkmenuplus-x86_64 works fine

**Comment by step-** [comment]
Thank you.

**Comment by plegrand1** [comment]
For my understanding, could you explain the difference between the two?

**Comment by step-** [comment]
Older hardware uses i686 binaries.  Modern hardware is all x86_64 or amd64 - these labels mean a 64bit CPU.

**Comment by plegrand1** [comment]
Thanks a lot. Now it works fine and  i understand !!
Thanks again
